markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Zach McCoy
url:
description: A fantastic blog that is fantastic.
twitter: ZachAMcCoy
github: zmccoy
gravatar_url: https://s.gravatar.com/avatar/006809bb41a2b67737831e7dcc69fbcc?s=80

