(function(){'use strict';
var e,g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=h;var aa="object"===typeof g.exportsNamespace&&g.exportsNamespace?g.exportsNamespace:h;g.exportsNamespace=aa;h.Object.freeze(g);var ba={envInfo:g,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.13"};h.Object.freeze(ba);h.Object.freeze(ba.semantics);
var n=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=h.WeakMap?new h.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.a||b.a.R!==c||b.a.P!==a)}}function fa(a){for(var b in a)return b}
function ga(a,b){return ha(a,b,0)}function ha(a,b,c){var d=new a.ib(b[c]);if(c<b.length-1){a=a.T;c+=1;for(var f=d.z,k=0;k<f.length;k++)f[k]=ha(a,b,c)}return d}function ia(a){return void 0===a?"undefined":a.toString()}
function ja(a){switch(typeof a){case "string":return r(ka);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?r(la):b<<16>>16===b&&1/b!==1/-0?r(ma):r(na):"number"===typeof a?r(oa):r(pa);case "boolean":return r(qa);case "undefined":return r(ra);default:return null===a?a.Gc():sa(a)?r(ta):a&&a.a?r(a.a):null}}
function ua(a){switch(typeof a){case "string":return va(t(),a);case "number":return wa(ya(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.m():null===ea?42:Aa(a)}}function Ba(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function Ca(a,b,c){a=Ba(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Da(a,b,c,d){a=Ba(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}function Ea(a,b,c){a=a.z;b=b.z;if(a!==b||0>0+c)for(var d=0;d<c;d++)b[0+d]=a[0+d];else for(d=c-1;0<=d;d--)b[0+d]=a[0+d]}
var Aa=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ua(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ua(a)};this.__ScalaJSExportsNamespace=aa;
function u(){this.ia=this.ib=void 0;this.P=this.T=this.l=null;this.R=0;this.gb=null;this.da="";this.o=this.ba=this.ca=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new u;d.l={};d.T=null;d.gb=a;d.da=b;d.o=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function w(a,b,c,d,f,k,m){var l=new u,p=fa(a);k=k||function(a){return!!(a&&a.a&&a.a.l[p])};m=m||function(a,b){return!!(a&&a.a&&a.a.R===b&&a.a.P.l[p])};l.ia=f;l.l=c;l.da="L"+b+";";l.o=m;l.name=b;l.isInterface=!1;l.isRawJSType=!!d;l.isInstance=k;return l}
function Fa(a){function b(a){if("number"===typeof a){this.z=Array(a);for(var b=0;b<a;b++)this.z[b]=f}else this.z=a}var c=new u,d=a.gb,f="longZero"==d?x().aa:d;b.prototype=new y;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.da,k=a.P||a,m=a.R+1;c.ib=b;c.ia=Ga;c.l={c:1,V:1,e:1};c.T=a;c.P=k;c.R=m;c.gb=null;c.da=d;c.ca=void 0;c.ba=void 0;c.o=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.o(a,m)};return c}
function r(a){if(!a.ca){var b=new z;b.ea=a;a.ca=b}return a.ca}function Ha(a){a.ba||(a.ba=Fa(a));return a.ba}u.prototype.getFakeInstance=function(){return this===ka?"some string":this===qa?!1:this===la||this===ma||this===na||this===oa||this===pa?0:this===ta?x().aa:this===ra?void 0:{a:this}};u.prototype.getSuperclass=function(){return this.ia?r(this.ia):null};u.prototype.getComponentType=function(){return this.T?r(this.T):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ha(b);return ga(b,a)};var Ia=v(!1,"Z","boolean"),Ja=v(0,"C","char"),Ka=v(0,"B","byte"),La=v(0,"S","short"),Ma=v(0,"I","int"),Pa=v("longZero","J","long"),Qa=v(0,"F","float"),Ra=v(0,"D","double");Ia.o=q(Ia);Ja.o=q(Ja);Ka.o=q(Ka);La.o=q(La);Ma.o=q(Ma);Pa.o=q(Pa);Qa.o=q(Qa);Ra.o=q(Ra);function A(){}function y(){}y.prototype=A.prototype;A.prototype.b=function(){return this};A.prototype.i=function(){var a=B(ja(this)),b=(+(this.m()>>>0)).toString(16);return a+"@"+b};A.prototype.m=function(){return Aa(this)};A.prototype.toString=function(){return this.i()};var Ga=w({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.R||0;return!(c<b)&&(c>b||!a.P.isPrimitive)}return!1});A.prototype.a=Ga;
function Sa(a){var b=a.K().G(),c=(new C).u(0);a.A(D(function(a,b,c){return function(a){b.J(Ta(a,c.d));c.d=1+c.d|0}}(a,b,c)));return b.H()}function Ua(a,b){var c=Va(a);a.A(D(function(a,b,c){return function(a){return b.J(c.s(a))}}(a,c,b)));return c.H()}function Va(a){var b=a.K().G();a&&a.a&&a.a.l.vb&&b.Y(a.E());return b}function Wa(a,b,c){var d=Xa();Ya(b.p,c);a.A(D(function(a,b,c,d){return function(a){if(b.d)Za(c,a),b.d=!1;else return Ya(c.p,d),Za(c,a)}}(a,d,b,", ")));Ya(b.p,")");return b}
function $a(a,b){var c;for(c=0;;)if(c<b&&a.h!==a)a=a.h,c=1+c|0;else break;c=a;if(!c.q())return c.U;throw(new E).n(""+b);}function ab(a,b){if(b>=a.r)throw(new E).n(""+b);return a.x.z[b]}function F(){}F.prototype=new y;F.prototype.constructor=F;F.prototype.b=function(){return this};
function bb(a){var b=a.getContext("2d");a.width=a.parentElement.clientWidth|0;a.height=400;b.font="50px sans-serif";b.textAlign="center";b.textBaseline="middle";var c=cb((a.height|0)/2),d=cb(0),f=(new C).u(0),k=(new C).u(-50),m=db().G().H();eb().setInterval(function(a,b,c,d,f,k,m,Oa,Zb,za){return function(){fb();b.clearRect(0,0,a.width|0,a.height|0);var gb;0<Oa.d?(k.d=(a.height|0)/2|0,m.d=0,Zb.d=-50,za.f=(new G).b(),za.j=za.f,za.g=0,Oa.d=-1+Oa.d|0,b.fillStyle="darkred",b.fillText("Game Over",(a.width|
0)/2|0,(a.height|0)/2|0),gb=void 0):gb=hb(a,b,c,d,f,k,m,Oa,Zb,za);return gb}}(a,b,200,50,.1,c,d,f,k,m),20);a.onclick=function(a){return function(){a.d=-5+a.d}}(d)}
function hb(a,b,c,d,f,k,m,l,p,V){p.d=2+p.d|0;if(0<=p.d&&0===(p.d%c|0)){ib||(ib=(new jb).b());for(var xa=[kb((a.height|0)-(d<<1)|0)+d|0],Na=0,Nc=xa.length|0;Na<Nc;)lb(V,xa[Na]),Na=1+Na|0}7<V.g&&(mb(V),p.d=p.d-c|0);k.d+=m.d;m.d+=f;b.fillStyle="darkblue";db();f=Sa(V);a=D(function(a,b,c,d,f,k,m){return function(l){if(null!==l){var p=l.Z|0;l=(n(l.$|0,c)-m.d|0)+(a.width|0)|0;b.fillRect(l,0,5,p-d|0);b.fillRect(l,p+d|0,5,((a.height|0)-p|0)-d|0);l=l-((a.width|0)/2|0)|0;5>(0>l?-l|0:l)&&+h.Math.abs(p-f.d)>d&&
(k.d=50);b.fillStyle="darkgreen";b.fillRect(-5+((a.width|0)/2|0)|0,-5+f.d,10,10);if(0>f.d||f.d>(a.height|0))k.d=50}else throw(new H).ab(l);}}(a,b,c,d,k,l,p));db();return Ua(f,a)}F.prototype.main=function(a){bb(a)};F.prototype.a=w({Fb:0},"example.ScalaJSExample$",{Fb:1,c:1});var nb=void 0;function fb(){nb||(nb=(new F).b());return nb}aa.example=aa.example||{};aa.example.ScalaJSExample=fb;function ob(){this.Eb=null;this.S=0}ob.prototype=new y;ob.prototype.constructor=ob;ob.prototype.b=function(){return this};
function eb(){var a;pb||(pb=(new ob).b());a=pb;0===(134217728&a.S)&&0===(134217728&a.S)&&(a.Eb=h,a.S|=134217728);return a.Eb}ob.prototype.a=w({Gb:0},"org.scalajs.dom.package$",{Gb:1,c:1});var pb=void 0;function z(){this.ea=null}z.prototype=new y;z.prototype.constructor=z;function B(a){return a.ea.name}z.prototype.i=function(){return(this.ea.isInterface?"interface ":this.ea.isPrimitive?"":"class ")+B(this)};z.prototype.a=w({Qb:0},"java.lang.Class",{Qb:1,c:1});function qb(){}qb.prototype=new y;
qb.prototype.constructor=qb;function rb(){}rb.prototype=qb.prototype;function sb(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);a^=b;return-430675100+n(5,a<<13|a>>>19|0)|0}function tb(a){a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function ub(a){vb();var b=a.sb();if(0===b)return a=a.ub(),va(t(),a);for(var c=-889275714,d=0;d<b;)c=sb(c,wb(xb(),a.tb(d))),d=1+d|0;return tb(c^b)}
function yb(a,b,c){var d=(new C).u(0);c=(new C).u(c);b.A(D(function(a,b,c){return function(a){c.d=sb(c.d,wb(xb(),a));b.d=1+b.d|0}}(a,d,c)));return tb(c.d^d.d)}function zb(){}zb.prototype=new y;zb.prototype.constructor=zb;function Ab(){}Ab.prototype=zb.prototype;function Bb(){this.I=!1;this.mb=this.fa=this.Q=null;this.Ya=!1;this.qb=this.nb=0}Bb.prototype=new y;Bb.prototype.constructor=Bb;
Bb.prototype.b=function(){Cb=this;this.Q=(this.I=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.fa=this.I?new h.Int32Array(this.Q,0,2):null;this.I&&new h.Float32Array(this.Q,0,2);this.mb=this.I?new h.Float64Array(this.Q,0,1):null;if(this.I)this.fa[0]=16909060,a=1===((new h.Int8Array(this.Q,0,8))[0]|0);else var a=!0;this.nb=(this.Ya=a)?0:1;this.qb=this.Ya?1:0;return this};
function wa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.I)a.mb[0]=b,a=(new I).M(a.fa[a.qb]|0,a.fa[a.nb]|0);else{if(b!==b)a=!1,b=2047,c=+h.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+h.Math.pow(2,-1022)){b=+h.Math.pow(2,52);var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,f=d/+h.Math.pow(2,c)*b,d=+h.Math.floor(f),f=f-d,d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/b&&(c=1+c|0,d=
1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+h.Math.pow(2,-1074),c=+h.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new I).M(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.F^a.B}Bb.prototype.a=w({wc:0},"scala.scalajs.runtime.Bits$",{wc:1,c:1});var Cb=void 0;function ya(){Cb||(Cb=(new Bb).b());return Cb}function Db(){this.S=!1}Db.prototype=new y;Db.prototype.constructor=Db;Db.prototype.b=function(){return this};
function Eb(a){if(0===(-65536&a))return h.String.fromCharCode(a);if(0>a||1114111<a)throw(new J).b();a=-65536+a|0;return h.String.fromCharCode(55296|a>>10,56320|1023&a)}function va(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}Db.prototype.a=w({yc:0},"scala.scalajs.runtime.RuntimeString$",{yc:1,c:1});var Fb=void 0;function t(){Fb||(Fb=(new Db).b());return Fb}function Gb(){}Gb.prototype=new y;Gb.prototype.constructor=Gb;
Gb.prototype.b=function(){return this};function Hb(a,b){return b&&b.a&&b.a.l.fb?b.L:b}function Ib(a,b){return b&&b.a&&b.a.l.W?b:(new Jb).ab(b)}Gb.prototype.a=w({zc:0},"scala.scalajs.runtime.package$",{zc:1,c:1});var Kb=void 0;function Lb(){Kb||(Kb=(new Gb).b());return Kb}function Mb(){}Mb.prototype=new y;Mb.prototype.constructor=Mb;Mb.prototype.b=function(){return this};
function wb(a,b){if(null===b)return 0;if(b&&b.a&&b.a.l.D||"number"===typeof b){if("number"===typeof b){a=+b;Nb||(Nb=(new K).b());b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=x();var c;if(-9223372036854775808>a)b.Ea=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.Ea=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.Ea=0>a&&0!==c?-1+d|0:d}b=b.Ea;x();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:wa(ya(),a)}return a}if(sa(b))return b=
null===b?x().aa:b,a=b.F,b=b.B,Nb||(Nb=(new K).b()),b=(new I).M(a,b),a=b.F,b=b.B,b===a>>31?a:a^b}return ua(b)}Mb.prototype.a=w({Ec:0},"scala.runtime.ScalaRunTime$",{Ec:1,c:1});var Ob=void 0;function xb(){Ob||(Ob=(new Mb).b());return Ob}function K(){}K.prototype=new y;K.prototype.constructor=K;K.prototype.b=function(){return this};K.prototype.a=w({Fc:0},"scala.runtime.Statics$",{Fc:1,c:1});var Nb=void 0;function Pb(){}Pb.prototype=new y;Pb.prototype.constructor=Pb;function Qb(){}Qb.prototype=Pb.prototype;
function L(){this.y=null}L.prototype=new y;L.prototype.constructor=L;function Rb(){}Rb.prototype=L.prototype;L.prototype.lb=function(){if(void 0===h.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=Ib(Lb(),b),null!==a)if(a&&a.a&&a.a.l.fb)a=a.L;else throw Hb(Lb(),a);else throw b;}this.stackdata=a}else h.Error.captureStackTrace(this),this.stackdata=this;return this};L.prototype.$a=function(){return this.y};L.prototype.i=function(){var a=B(ja(this)),b=this.$a();return null===b?a:a+": "+b};
L.prototype.C=function(a){this.y=a;this.lb();return this};function M(){this.db=this.cb=0}M.prototype=new y;M.prototype.constructor=M;M.prototype.b=function(){M.prototype.Kb.call(this,Sb());return this};M.prototype.Kb=function(a){var b=-554899859^a.F;this.cb=b>>>24|0|(65535&(5^a.B))<<8;this.db=16777215&b;return this};
function kb(a){var b=ib.w;if(0>=a)throw(new J).n("n must be positive");if((a&(-a|0))===a)a=Tb(b)>>ca(a);else a:for(;;){var c=Tb(b),d=c%a|0;if(!(0>((c-d|0)+(-1+a|0)|0))){a=d;break a}}return a}function Tb(a){var b=a.db,c=11+15525485*b,b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.cb|0))|0),c=16777215&(c|0);a.cb=b;a.db=c;return(b<<8|c>>16)>>>1|0}M.prototype.a=w({$b:0},"java.util.Random",{$b:1,c:1,e:1});function Ub(){this.eb=0}Ub.prototype=new rb;Ub.prototype.constructor=Ub;
Ub.prototype.b=function(){Vb=this;this.eb=va(t(),"Seq");va(t(),"Map");va(t(),"Set");return this};function Wb(a){var b=vb(),c;if(a&&a.a&&a.a.l.Tc){c=0;for(var b=b.eb,d=a;!d.q();)a=Xb(d),d=d.bd(),b=sb(b,wb(xb(),a)),c=1+c|0;c=tb(b^c)}else c=yb(b,a,b.eb);return c}Ub.prototype.a=w({ec:0},"scala.util.hashing.MurmurHash3$",{ec:1,Mc:1,c:1});var Vb=void 0;function vb(){Vb||(Vb=(new Ub).b());return Vb}function N(){}N.prototype=new Ab;N.prototype.constructor=N;function Yb(){}Yb.prototype=N.prototype;
N.prototype.b=function(){(new $b).bb(this);return this};function ac(){}ac.prototype=new y;ac.prototype.constructor=ac;function bc(){}bc.prototype=ac.prototype;ac.prototype.bb=function(a){if(null===a)throw Hb(Lb(),null);return this};function cc(){}cc.prototype=new y;cc.prototype.constructor=cc;function dc(){}dc.prototype=cc.prototype;cc.prototype.i=function(){return"\x3cfunction1\x3e"};function ec(){this.d=!1}ec.prototype=new y;ec.prototype.constructor=ec;ec.prototype.i=function(){return""+this.d};
function Xa(){var a=new ec;a.d=!0;return a}ec.prototype.a=w({Ac:0},"scala.runtime.BooleanRef",{Ac:1,c:1,e:1});var ra=w({Bc:0},"scala.runtime.BoxedUnit",{Bc:1,c:1,e:1},void 0,void 0,function(a){return void 0===a});function fc(){this.d=0}fc.prototype=new y;fc.prototype.constructor=fc;function cb(a){var b=new fc;b.d=a;return b}fc.prototype.i=function(){return""+this.d};fc.prototype.a=w({Cc:0},"scala.runtime.DoubleRef",{Cc:1,c:1,e:1});function C(){this.d=0}C.prototype=new y;C.prototype.constructor=C;
C.prototype.i=function(){return""+this.d};C.prototype.u=function(a){this.d=a;return this};C.prototype.a=w({Dc:0},"scala.runtime.IntRef",{Dc:1,c:1,e:1});var qa=w({Nb:0},"java.lang.Boolean",{Nb:1,c:1,e:1,v:1},void 0,void 0,function(a){return"boolean"===typeof a});function O(){this.Xa=0}O.prototype=new y;O.prototype.constructor=O;O.prototype.i=function(){return h.String.fromCharCode(this.Xa)};function gc(a){var b=new O;b.Xa=a;return b}O.prototype.m=function(){return this.Xa};
O.prototype.a=w({Pb:0},"java.lang.Character",{Pb:1,c:1,e:1,v:1});function hc(){this.y=null}hc.prototype=new Rb;hc.prototype.constructor=hc;function ic(){}ic.prototype=hc.prototype;function jc(){}jc.prototype=new y;jc.prototype.constructor=jc;jc.prototype.b=function(){return this};function Sb(){kc||(kc=(new jc).b());var a=lc(),b=lc();return(new I).M(b,a)}function lc(){var a=4294967296*+h.Math.random(),a=-2147483648+ +h.Math.floor(a);return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}
jc.prototype.a=w({ac:0},"java.util.Random$",{ac:1,c:1,k:1,e:1});var kc=void 0;function mc(){this.w=null}mc.prototype=new y;mc.prototype.constructor=mc;function nc(){}nc.prototype=mc.prototype;mc.prototype.Mb=function(a){this.w=a;return this};function oc(){}oc.prototype=new Yb;oc.prototype.constructor=oc;function pc(){}pc.prototype=oc.prototype;function $b(){}$b.prototype=new bc;$b.prototype.constructor=$b;$b.prototype.bb=function(a){if(null===a)throw Hb(Lb(),null);ac.prototype.bb.call(this,a);return this};
$b.prototype.a=w({ic:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{ic:1,Qc:1,c:1,Pc:1});function qc(){this.kb=null}qc.prototype=new dc;qc.prototype.constructor=qc;qc.prototype.s=function(a){return(0,this.kb)(a)};function D(a){var b=new qc;b.kb=a;return b}qc.prototype.a=w({vc:0},"scala.scalajs.runtime.AnonFunction1",{vc:1,ad:1,c:1,O:1});function rc(){this.Ea=0;this.aa=null}rc.prototype=new y;rc.prototype.constructor=rc;rc.prototype.b=function(){sc=this;this.aa=(new I).M(0,0);return this};
function tc(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,k=a,m=b;for(a=b=0;0<=c&&0!==(-2097152&m);){var l=k,p=m,V=f,xa=d;if(p===xa?(-2147483648^l)>=(-2147483648^V):(-2147483648^p)>=(-2147483648^xa))l=m,p=d,m=k-f|0,l=(-2147483648^m)>(-2147483648^k)?-1+(l-p|0)|0:l-p|0,k=m,m=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;f=f>>>1|0|d<<31;d=l}c=m;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*m+ +(k>>>0),k=c/1E9,f=k/4294967296|0,d=b,b=k=d+(k|0)|0,a=(-2147483648^k)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,c%=1E9,k=c|0,m=c/4294967296|0;b=[b,a,k,m];a=""+(b["2"]|0);return""+(4294967296*(b["1"]|0)+ +((b["0"]|0)>>>0))+"000000000".substring(a.length|0)+a}rc.prototype.a=w({xc:0},"scala.scalajs.runtime.RuntimeLong$",{xc:1,c:1,k:1,e:1});var sc=void 0;function x(){sc||(sc=(new rc).b());return sc}
var ka=w({Hb:0},"java.lang.String",{Hb:1,c:1,e:1,pb:1,v:1},void 0,void 0,function(a){return"string"===typeof a}),la=w({Ob:0},"java.lang.Byte",{Ob:1,D:1,c:1,e:1,v:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),pa=w({Rb:0},"java.lang.Double",{Rb:1,D:1,c:1,e:1,v:1},void 0,void 0,function(a){return"number"===typeof a}),oa=w({Sb:0},"java.lang.Float",{Sb:1,D:1,c:1,e:1,v:1},void 0,void 0,function(a){return"number"===typeof a}),na=w({Vb:0},"java.lang.Integer",{Vb:1,D:1,c:1,e:1,v:1},void 0,
void 0,function(a){return(a|0)===a&&1/a!==1/-0}),ta=w({Wb:0},"java.lang.Long",{Wb:1,D:1,c:1,e:1,v:1},void 0,void 0,function(a){return sa(a)});function uc(){this.y=null}uc.prototype=new ic;uc.prototype.constructor=uc;function vc(){}vc.prototype=uc.prototype;var ma=w({Xb:0},"java.lang.Short",{Xb:1,D:1,c:1,e:1,v:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function P(){this.t=null}P.prototype=new y;P.prototype.constructor=P;
function Ya(a,b){a.t=""+a.t+(null===b?"null":b);return a}P.prototype.i=function(){return this.t};P.prototype.u=function(){P.prototype.n.call(this,"");return this};P.prototype.n=function(a){this.t=a;return this};P.prototype.a=w({Yb:0},"java.lang.StringBuilder",{Yb:1,c:1,pb:1,Hc:1,e:1});function jb(){this.w=null}jb.prototype=new nc;jb.prototype.constructor=jb;jb.prototype.b=function(){mc.prototype.Mb.call(this,(new M).b());return this};
jb.prototype.a=w({dc:0},"scala.util.Random$",{dc:1,Lc:1,c:1,k:1,e:1});var ib=void 0;function I(){this.B=this.F=0}I.prototype=new Qb;I.prototype.constructor=I;e=I.prototype;e.i=function(){x();var a=this.F,b=this.B;return b===a>>31?""+a:0>b?"-"+tc(-a|0,0!==a?~b:-b|0):tc(a,b)};e.M=function(a,b){this.F=a;this.B=b;return this};e.u=function(a){I.prototype.M.call(this,a,a>>31);return this};e.m=function(){return this.F^this.B};function sa(a){return!!(a&&a.a&&a.a.l.Ab)}
e.a=w({Ab:0},"scala.scalajs.runtime.RuntimeLong",{Ab:1,D:1,c:1,e:1,v:1});function J(){this.y=null}J.prototype=new vc;J.prototype.constructor=J;J.prototype.b=function(){L.prototype.C.call(this,null);return this};J.prototype.n=function(a){L.prototype.C.call(this,a);return this};J.prototype.a=w({Tb:0},"java.lang.IllegalArgumentException",{Tb:1,ha:1,ga:1,W:1,c:1,e:1});function E(){this.y=null}E.prototype=new vc;E.prototype.constructor=E;E.prototype.n=function(a){L.prototype.C.call(this,a);return this};
E.prototype.a=w({Ub:0},"java.lang.IndexOutOfBoundsException",{Ub:1,ha:1,ga:1,W:1,c:1,e:1});function Q(){this.y=null}Q.prototype=new vc;Q.prototype.constructor=Q;Q.prototype.b=function(){L.prototype.C.call(this,null);return this};Q.prototype.n=function(a){L.prototype.C.call(this,a);return this};Q.prototype.a=w({Zb:0},"java.util.NoSuchElementException",{Zb:1,ha:1,ga:1,W:1,c:1,e:1});function H(){this.rb=this.X=this.y=null;this.Za=!1}H.prototype=new vc;H.prototype.constructor=H;
H.prototype.$a=function(){if(!this.Za&&!this.Za){var a;if(null===this.X)a="null";else try{a=ia(this.X)+" ("+("of class "+B(ja(this.X)))+")"}catch(b){if(null!==Ib(Lb(),b))a="an instance of class "+B(ja(this.X));else throw b;}this.rb=a;this.Za=!0}return this.rb};H.prototype.ab=function(a){this.X=a;L.prototype.C.call(this,null);return this};H.prototype.a=w({bc:0},"scala.MatchError",{bc:1,ha:1,ga:1,W:1,c:1,e:1});function wc(){this.jb=this.w=null}wc.prototype=new y;wc.prototype.constructor=wc;
function xc(a,b,c){a.jb=c;a.w=b;return a}e=wc.prototype;e.i=function(){return""+this.w};e.H=function(){return this.jb.s(this.w.H())};e.J=function(a){this.w.J(a);return this};e.m=function(){return this.w.m()};e.Y=function(a){this.w.Y(a)};e.a=w({lc:0},"scala.collection.mutable.Builder$$anon$1",{lc:1,c:1,Ra:1,Ma:1,Fa:1,Jc:1});function yc(){this.$=this.Z=null}yc.prototype=new y;yc.prototype.constructor=yc;e=yc.prototype;e.ub=function(){return"Tuple2"};e.sb=function(){return 2};
e.tb=function(a){a:switch(a){case 0:a=this.Z;break a;case 1:a=this.$;break a;default:throw(new E).n(""+a);}return a};function Ta(a,b){var c=new yc;c.Z=a;c.$=b;return c}e.i=function(){return"("+this.Z+","+this.$+")"};e.m=function(){return ub(this)};e.a=w({Ib:0},"scala.Tuple2",{Ib:1,c:1,Ic:1,cc:1,N:1,k:1,e:1});function zc(){}zc.prototype=new pc;zc.prototype.constructor=zc;function Ac(){}Ac.prototype=zc.prototype;function R(){}R.prototype=new Ac;R.prototype.constructor=R;
R.prototype.b=function(){N.prototype.b.call(this);return this};R.prototype.G=function(){return(new S).b()};R.prototype.a=w({nc:0},"scala.collection.mutable.IndexedSeq$",{nc:1,Oa:1,Ha:1,Ia:1,Ja:1,c:1,Pa:1,Ka:1});var Bc=void 0;function Jb(){this.L=this.y=null}Jb.prototype=new vc;Jb.prototype.constructor=Jb;e=Jb.prototype;e.ub=function(){return"JavaScriptException"};e.sb=function(){return 1};e.lb=function(){this.stackdata=this.L;return this};
e.tb=function(a){switch(a){case 0:return this.L;default:throw(new E).n(""+a);}};e.$a=function(){return ia(this.L)};e.ab=function(a){this.L=a;L.prototype.C.call(this,null);return this};e.m=function(){return ub(this)};e.a=w({fb:0},"scala.scalajs.js.JavaScriptException",{fb:1,ha:1,ga:1,W:1,c:1,e:1,cc:1,N:1,k:1});function T(){}T.prototype=new Ac;T.prototype.constructor=T;T.prototype.b=function(){N.prototype.b.call(this);return this};T.prototype.G=function(){return(new S).b()};
T.prototype.a=w({kc:0},"scala.collection.mutable.ArrayBuffer$",{kc:1,Oa:1,Ha:1,Ia:1,Ja:1,c:1,Pa:1,Ka:1,k:1,e:1});var Cc=void 0;function U(){}U.prototype=new Ac;U.prototype.constructor=U;U.prototype.b=function(){N.prototype.b.call(this);return this};U.prototype.G=function(){var a=(new W).b();return xc(new wc,a,D(function(){return function(a){return a.f}}(this)))};U.prototype.a=w({qc:0},"scala.collection.mutable.LinkedList$",{qc:1,Oa:1,Ha:1,Ia:1,Ja:1,c:1,Pa:1,Ka:1,k:1,e:1});var Dc=void 0;
function X(){}X.prototype=new Ac;X.prototype.constructor=X;X.prototype.b=function(){N.prototype.b.call(this);return this};X.prototype.G=function(){return(new W).b()};X.prototype.a=w({rc:0},"scala.collection.mutable.MutableList$",{rc:1,Oa:1,Ha:1,Ia:1,Ja:1,c:1,Pa:1,Ka:1,k:1,e:1});var Ec=void 0;function Y(){}Y.prototype=new Ac;Y.prototype.constructor=Y;Y.prototype.b=function(){N.prototype.b.call(this);return this};
Y.prototype.G=function(){var a=(new W).b();return xc(new wc,a,D(function(){return function(a){var c=a.f,d=a.j;a=a.g;var f=new Fc;W.prototype.b.call(f);f.f=c;f.j=d;f.g=a;return f}}(this)))};Y.prototype.a=w({tc:0},"scala.collection.mutable.Queue$",{tc:1,Oa:1,Ha:1,Ia:1,Ja:1,c:1,Pa:1,Ka:1,k:1,e:1});var Gc=void 0;function db(){Gc||(Gc=(new Y).b());return Gc}function Hc(){}Hc.prototype=new y;Hc.prototype.constructor=Hc;function Ic(){}Ic.prototype=Hc.prototype;
Hc.prototype.Bb=function(){var a=B(ja(this)),b;t();b=a;var c=Eb(46);b=b.lastIndexOf(c)|0;-1!==b&&(a=a.substring(1+b|0));t();b=a;c=Eb(36);b=b.indexOf(c)|0;-1!==b&&(a=a.substring(0,b));return a};function Jc(){}Jc.prototype=new Ic;Jc.prototype.constructor=Jc;function Kc(){}Kc.prototype=Jc.prototype;function Lc(){}Lc.prototype=new Kc;Lc.prototype.constructor=Lc;function Mc(){}Mc.prototype=Lc.prototype;Lc.prototype.i=function(){var a=this.Bb()+"(",b=(new Z).b();return Wa(this,b,a).p.t};
function Oc(){}Oc.prototype=new Mc;Oc.prototype.constructor=Oc;function Pc(){}Pc.prototype=Oc.prototype;function G(){this.h=this.U=null}G.prototype=new Pc;G.prototype.constructor=G;e=G.prototype;e.b=function(){this.h=this;return this};e.s=function(a){return $a(this,a|0)};e.q=function(){return this.h===this};e.K=function(){Dc||(Dc=(new U).b());return Dc};e.A=function(a){for(var b=this;!b.q();)a.s(b.U),b=b.h};e.E=function(){a:{var a=this,b=0;for(;;){if(a.h===a)break a;b=1+b|0;a=a.h}}return b};e.m=function(){return Wb(this)};
e.a=w({pc:0},"scala.collection.mutable.LinkedList",{pc:1,Qa:1,na:1,ma:1,oa:1,c:1,Ba:1,Ca:1,Na:1,Ga:1,Da:1,va:1,ua:1,ya:1,ta:1,La:1,wa:1,pa:1,qa:1,xa:1,N:1,za:1,la:1,O:1,ra:1,sa:1,Aa:1,Ua:1,Ta:1,Wa:1,ka:1,Va:1,Sa:1,ja:1,V:1,yb:1,wb:1,xb:1,Zc:1,k:1,e:1});function Qc(){}Qc.prototype=new Pc;Qc.prototype.constructor=Qc;function Rc(){}Rc.prototype=Qc.prototype;function W(){this.j=this.f=null;this.g=0}W.prototype=new Pc;W.prototype.constructor=W;function Sc(){}Sc.prototype=W.prototype;
function Xb(a){if(!a.q()){a=a.f;if(a.h===a)throw(new Q).b();return a.U}throw(new Q).b();}e=W.prototype;e.b=function(){this.j=this.f=(new G).b();this.g=0;return this};e.s=function(a){return $a(this.f,a|0)};e.q=function(){return 0===this.g};e.K=function(){Ec||(Ec=(new X).b());return Ec};e.A=function(a){for(var b=this;!b.q();)a.s(Xb(b)),b=b.Cb()};
function Tc(a,b){if(a.q())throw(new J).n("requirement failed: tail of empty list");var c=a.f;if(c.q())throw(new J).n("requirement failed: tail of empty list");b.f=c.h;b.g=-1+a.g|0;b.j=0===b.g?b.f:a.j}e.H=function(){return this};e.E=function(){return this.g};e.Cb=function(){return this.Db()};e.J=function(a){return lb(this,a)};e.Y=function(){};e.m=function(){return Wb(this)};
function lb(a,b){if(0===a.g){var c=a.f,d=new G;G.prototype.b.call(d);null!==c&&(d.U=b,d.h=c);a.f=d;0===a.g&&(a.j=a.f)}else a.j.h=(new G).b(),a.j=a.j.h,a.j.U=b,a.j.h=(new G).b();a.g=1+a.g|0;return a}e.Db=function(){var a=(new W).b();Tc(this,a);return a};
e.a=w({zb:0},"scala.collection.mutable.MutableList",{zb:1,Qa:1,na:1,ma:1,oa:1,c:1,Ba:1,Ca:1,Na:1,Ga:1,Da:1,va:1,ua:1,ya:1,ta:1,La:1,wa:1,pa:1,qa:1,xa:1,N:1,za:1,la:1,O:1,ra:1,sa:1,Aa:1,Ua:1,Ta:1,Wa:1,ka:1,Va:1,Sa:1,ja:1,V:1,yb:1,wb:1,xb:1,hc:1,Ra:1,Ma:1,Fa:1,k:1,e:1});function Fc(){W.call(this)}Fc.prototype=new Sc;Fc.prototype.constructor=Fc;e=Fc.prototype;e.b=function(){W.prototype.b.call(this);return this};
function mb(a){if(a.q())throw(new Q).n("queue empty");a.f=a.f.h;a.g=-1+a.g|0;0===a.g&&(a.j=a.f)}e.K=function(){return db()};e.Cb=function(){return Uc(this)};function Uc(a){var b=(new Fc).b();Tc(a,b);return b}e.Db=function(){return Uc(this)};
e.a=w({sc:0},"scala.collection.mutable.Queue",{sc:1,zb:1,Qa:1,na:1,ma:1,oa:1,c:1,Ba:1,Ca:1,Na:1,Ga:1,Da:1,va:1,ua:1,ya:1,ta:1,La:1,wa:1,pa:1,qa:1,xa:1,N:1,za:1,la:1,O:1,ra:1,sa:1,Aa:1,Ua:1,Ta:1,Wa:1,ka:1,Va:1,Sa:1,ja:1,V:1,yb:1,wb:1,xb:1,hc:1,Ra:1,Ma:1,Fa:1,k:1,e:1});function Z(){this.p=null}Z.prototype=new Pc;Z.prototype.constructor=Z;e=Z.prototype;e.b=function(){Z.prototype.Jb.call(this,16,"");return this};e.hb=function(a){a=65535&(this.p.t.charCodeAt(a)|0);return gc(a)};
e.s=function(a){a=65535&(this.p.t.charCodeAt(a|0)|0);return gc(a)};e.q=function(){return 0===this.E()};e.i=function(){return this.p.t};e.K=function(){Bc||(Bc=(new R).b());return Bc};e.A=function(a){for(var b=0,c=this.E();b<c;)a.s(this.hb(b)),b=1+b|0};e.H=function(){return this.p.t};e.Jb=function(a,b){Z.prototype.Lb.call(this,Ya((new P).u((b.length|0)+a|0),b));return this};e.E=function(){return this.p.t.length|0};e.Lb=function(a){this.p=a;return this};
function Za(a,b){var c=a.p;t();Ya(c,null===b?"null":ia(b));return a}e.J=function(a){Ya(this.p,h.String.fromCharCode(null===a?0:a.Xa));return this};e.Y=function(){};e.m=function(){return Wb(this)};e.a=w({uc:0},"scala.collection.mutable.StringBuilder",{uc:1,Qa:1,na:1,ma:1,oa:1,c:1,Ba:1,Ca:1,Na:1,Ga:1,Da:1,va:1,ua:1,ya:1,ta:1,La:1,wa:1,pa:1,qa:1,xa:1,N:1,za:1,la:1,O:1,ra:1,sa:1,Aa:1,Ua:1,Ta:1,Wa:1,ka:1,Va:1,Sa:1,ja:1,V:1,pb:1,mc:1,fc:1,vb:1,oc:1,Uc:1,gc:1,Kc:1,v:1,Ra:1,Ma:1,Fa:1,k:1,e:1});
function S(){this.ob=0;this.x=null;this.r=0}S.prototype=new Rc;S.prototype.constructor=S;e=S.prototype;e.b=function(){S.prototype.u.call(this,16);return this};e.hb=function(a){return ab(this,a)};e.s=function(a){return ab(this,a|0)};e.q=function(){return 0===this.E()};e.K=function(){Cc||(Cc=(new T).b());return Cc};e.A=function(a){for(var b=0,c=this.r;b<c;)a.s(this.x.z[b]),b=1+b|0};e.H=function(){return this};e.u=function(a){a=this.ob=a;this.x=ga(Ha(Ga),[1<a?a:1]);this.r=0;return this};e.E=function(){return this.r};
e.J=function(a){var b=1+this.r|0,c=this.x.z.length,d=c>>31,f=b>>31;if(f===d?(-2147483648^b)>(-2147483648^c):f>d){f=c<<1;for(c=c>>>31|0|d<<1;;){var d=b>>31,k=f,m=c;if(d===m?(-2147483648^b)>(-2147483648^k):d>m)c=f>>>31|0|c<<1,f<<=1;else break}b=c;if(0===b?-1<(-2147483648^f):0<b)f=2147483647;b=f;b=ga(Ha(Ga),[b]);Ea(this.x,b,this.r);this.x=b}this.x.z[this.r]=a;this.r=1+this.r|0;return this};e.m=function(){return Wb(this)};e.Y=function(a){a>this.r&&1<=a&&(a=ga(Ha(Ga),[a]),Ea(this.x,a,this.r),this.x=a)};
e.Bb=function(){return"ArrayBuffer"};e.a=w({jc:0},"scala.collection.mutable.ArrayBuffer",{jc:1,Vc:1,Qa:1,na:1,ma:1,oa:1,c:1,Ba:1,Ca:1,Na:1,Ga:1,Da:1,va:1,ua:1,ya:1,ta:1,La:1,wa:1,pa:1,qa:1,xa:1,N:1,za:1,la:1,O:1,ra:1,sa:1,Aa:1,Ua:1,Ta:1,Wa:1,ka:1,Va:1,Sa:1,ja:1,V:1,Wc:1,Xc:1,Ma:1,Fa:1,Rc:1,Oc:1,Sc:1,Yc:1,oc:1,vb:1,gc:1,Ra:1,$c:1,mc:1,fc:1,Nc:1,k:1,e:1});
}).call(this);
//# sourceMappingURL=example-opt.js.map

